name: CI

on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/cache@v3
        with:
          path: |
            ~/.nuget/packages
            ~/.cache/bepinex
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          verbosity: Diagnostic

      - name: Create ZIP with artifacts
        run: |
          mkdir -p output
          cp Reactor/bin/Release/net6.0/Reactor.dll output/
          cp Reactor/bin/Release/Reactor.*.nupkg output/
          cp Reactor.Networking.Shared/bin/Release/*.nupkg output/
          cp Reactor.Debugger/bin/Release/net6.0/Reactor.Debugger.dll output/
          zip -r artifacts.zip output

      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: artifacts.zip

      - uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: artifacts.zip

      - name: Push nightly NuGet package
        if: github.repository == 'NuclearPowered/Reactor' && github.ref == 'refs/heads/master'
        run: |
          dotnet nuget push Reactor/bin/Release/Reactor.*.nupkg --source https://nuget.reactor.gg/v3/index.json --api-key ${{ secrets.REACTOR_NUGET_KEY }}
          dotnet nuget push Reactor.Networking.Shared/bin/Release/*.nupkg --source https://nuget.reactor.gg/v3/index.json --api-key ${{ secrets.REACTOR_NUGET_KEY }}
